#
# Makefile
# Compiles the compiler
#
# IFJ project 2025
# FIT VUT
#
# Authors:
# Michal Šebesta (xsebesm00)
#
CC = gcc
CFLAGS += -Wall -Wextra -pedantic -std=c11
LDLIBS += -lm
# CFLAGS += -Werror
# CFLAGS += -O3

# Debugging
# CFLAGS += -g -DCG_DEBUG
# Asan
# CFLAGS += -fsanitize=address
# LDFLAGS += -lasan

ZIPNAME=xsebesm00.zip

main: main.o ast.o code_generator.o vojta.o lexer.o parser.o stack.o string.o symtable.o token.o optimizer.o

doc: dokumentace.pdf
dokumentace.pdf: doc/dokumentace.tex
	(cd doc; pdflatex dokumentace.tex)
	(cd doc; pdflatex dokumentace.tex)
	mv doc/dokumentace.pdf .

.PHONY: clean
clean:
	rm *.o
	rm doc/*.aux doc/*.dvi doc/*.log doc/*.out doc/*.toc

.PHONY: pack
pack: doc
	zip $(ZIPNAME) *.c *.h rozdeleni rozsireni Makefile dokumentace.pdf

# Generated by `gcc -MM *.c`
ast.o: ast.c ast.h string.h symtable.h
code_generator.o: code_generator.c code_generator.h ast.h string.h \
 error.h symtable.h
vojta.o: vojta.c vojta.h stack.h token.h string.h ast.h \
 lexer.h error.h
lexer.o: lexer.c lexer.h string.h token.h ast.h
main.o: main.c ast.h string.h code_generator.h error.h symtable.h \
 parser.h lexer.h token.h optimizer.h
optimizer.o: optimizer.c optimizer.h ast.h string.h error.h symtable.h
parser.o: parser.c parser.h lexer.h string.h token.h ast.h error.h \
 symtable.h vojta.h stack.h
stack.o: stack.c stack.h token.h string.h ast.h
string.o: string.c string.h
symtable.o: symtable.c symtable.h string.h ast.h
token.o: token.c token.h string.h ast.h
