#
# Makefile
# Compiles the compiler
#
# Authors:
# Michal Šebesta (xsebesm00)
#
CC = gcc
CFLAGS += -Wall -Wextra -pedantic
# CFLAGS += -Werror
# CFLAGS += -O3

# Debugging
CFLAGS += -g -DCG_DEBUG
# Asan
# CFLAGS += -fsanitize=address
# LDFLAGS += -lasan

main: main.o ast.o code_generator.o expr_parser.o lexer.o parser.o stack.o string.o symtable.o token.o optimizer.o

.PHONY: clean
clean:
	rm *.o

# Generated by `gcc -MM *.c`
ast.o: ast.c ast.h string.h symtable.h
code_generator.o: code_generator.c code_generator.h ast.h string.h \
 error.h symtable.h
expr_parser.o: expr_parser.c expr_parser.h stack.h token.h string.h ast.h \
 lexer.h error.h
lexer.o: lexer.c lexer.h string.h token.h ast.h
lex-test.o: lex-test.c lexer.h string.h token.h ast.h
main.o: main.c ast.h string.h code_generator.h error.h symtable.h \
 parser.h lexer.h token.h
parser.o: parser.c parser.h lexer.h string.h token.h ast.h error.h \
 symtable.h expr_parser.h stack.h
stack.o: stack.c stack.h token.h string.h ast.h
string.o: string.c string.h
symtable.o: symtable.c symtable.h string.h ast.h
token.o: token.c token.h string.h ast.h
optimizer.o: optimizer.c optimizer.h ast.h error.h symtable.h string.h